apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: argocd-demo
  labels:
    app: nginx
spec:
  externalTrafficPolicy: Local
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:    
    app: nginx
  type: NodePort
